"""Release package contract tests using only the Python standard library."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]
INTEGRATION = ROOT / "custom_components" / "orvibo_lan"


class PackageContractTests(unittest.TestCase):
    def test_legacy_compatibility_clients_keep_tls_and_secrets_safe(self) -> None:
        https_client = (INTEGRATION / "lib" / "https_client.py").read_text(encoding="utf-8")
        lan_controller = (INTEGRATION / "lib" / "lan_controller.py").read_text(encoding="utf-8")

        self.assertNotIn("ssl=False", https_client)
        self.assertNotIn("Hello 回复: {parsed}", lan_controller)
        self.assertNotIn("payload={payload}", lan_controller)

    def test_services_only_describe_registered_features(self) -> None:
        services = (INTEGRATION / "services.yaml").read_text(encoding="utf-8")

        self.assertIn("refresh_devices:", services)
        self.assertNotIn("clothes_horse_control:", services)

    """Verify metadata and the real ZIP generated by the release entry point."""

    def test_versions_and_compatibility_are_manifest_driven(self) -> None:
        manifest = json.loads((INTEGRATION / "manifest.json").read_text(encoding="utf-8"))
        hacs = json.loads((ROOT / "hacs.json").read_text(encoding="utf-8"))
        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")

        self.assertEqual(manifest["domain"], "orvibo_lan")
        self.assertEqual(manifest["version"], "0.1.0")
        self.assertEqual(manifest["codeowners"], ["@maycode0-0"])
        self.assertEqual(
            manifest["documentation"],
            "https://github.com/maycode0-0/orvibo-lan",
        )
        self.assertEqual(
            manifest["issue_tracker"],
            "https://github.com/maycode0-0/orvibo-lan/issues",
        )
        self.assertEqual(hacs["homeassistant"], "2024.1.0")
        self.assertEqual(hacs["filename"], "orvibo_lan.zip")
        self.assertTrue(hacs["zip_release"])
        self.assertFalse(hacs["content_in_root"])
        self.assertNotRegex(pyproject, r"(?m)^\s*version\s*=")
        self.assertIn('dynamic = ["version"]', pyproject)
        self.assertIn('requires-python = ">=3.11"', pyproject)

    def test_release_entry_point_builds_flat_complete_zip(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            archive_path = Path(temporary_directory) / "orvibo_lan.zip"
            subprocess.run(
                [sys.executable, str(ROOT / "scripts" / "build_release.py"), str(archive_path)],
                cwd=ROOT,
                check=True,
            )

            self.assertGreater(archive_path.stat().st_size, 0)
            with zipfile.ZipFile(archive_path) as archive:
                names = set(archive.namelist())
                expected = {
                    PurePosixPath(*source.relative_to(INTEGRATION).parts).as_posix()
                    for source in INTEGRATION.rglob("*")
                    if source.is_file()
                    and "__pycache__" not in source.relative_to(INTEGRATION).parts
                    and source.suffix not in {".pyc", ".pyo"}
                }
                self.assertEqual(names, expected)
                self.assertTrue(
                    {
                        "manifest.json",
                        "__init__.py",
                        "services.yaml",
                        "translations/en.json",
                        "brand/icon.png",
                    }.issubset(names)
                )
                for name in names:
                    path = PurePosixPath(name)
                    self.assertFalse(path.is_absolute(), name)
                    self.assertNotIn("..", path.parts, name)
                    self.assertFalse(name.startswith(("custom_components/", "orvibo_lan/")), name)
                archived_manifest = json.loads(archive.read("manifest.json").decode("utf-8"))

        self.assertEqual(
            archived_manifest,
            json.loads((INTEGRATION / "manifest.json").read_text(encoding="utf-8")),
        )


if __name__ == "__main__":
    unittest.main()
